### ISSUE TITLE
New Name?

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-nitro#181]
APEX Live Reload??? Joel please make your suggestions.

**Comment by vincentmorneau** [comment]
Joel?

Why a new name?

**Comment by vincentmorneau** [comment]
I am open minded about a new name, but I do like "APEX Front-End Boost" already for many reasons:

1 - It doesn't focus only on the Browsersync aspect of the tool (as opposed to APEX Live Reload) and that's good because AFEB does much more
2 - It states the type of technology it's targeting
3 - It indicates that it's a productivity tool (`Boost`)

Also, another thing to consider is that a name change at this point also required a considerable code change (CLI uses the `afeb` all over), change to the npm registry, docs, etc.

If a new name suggestion meets at least two of these criteria, we can start thinking about it, but APEX Live Reload is the opposite of what I envision. I'm also more inclined to drop the `APEX` part of the name.

**Comment by vincentmorneau** [comment]
Just writing this here after our conversation... Idea was: WAM _(Web Asset Manager)_

**Comment by vincentmorneau** [comment]
Here's a survey that I did on Twitter. Final results will help decide on whether we change the name or not:
https://twitter.com/vincentmorneau/status/845255620727070720

**Comment by vincentmorneau** [comment]
More ideas:
- APEX Plasma
- APEX Adroit
- APEX Deft

I am leaning toward Plasma for now.
