### ISSUE TITLE
Code Editor theme css file not found

### ISSUE THREAD

**Issue by Divyashree-Ramesh** [OraOpenSource/apex-nitro#243]
### Issue Description
Code Editor theme CSS file not found.

### APEX Nitro Version
v4.0.0

### Operating System
Windows 10

### Node Version
v8.9.4

### Browser
Chrome v64.0.3282.140

### APEX Version
v5.1.2

### Web Server
Tomcat

### Project configuration screenshot
![config](https://user-images.githubusercontent.com/23319765/36322380-e5973c20-1301-11e8-8ddf-29736e52a32c.png)

**Comment by vincentmorneau** [comment]
Hi,

Thanks for the configuration screenshot. 

Can you also post a screenshot of the `src` folder?
Also a screenshot of your erro message in the console?

**Comment by Divyashree-Ramesh** [comment]
Hi,

Here is the screenshot.
![error scr](https://user-images.githubusercontent.com/23319765/36323522-0a7819e8-1306-11e8-9959-7c7f78016730.png)
![error](https://user-images.githubusercontent.com/23319765/36323542-1f950b92-1306-11e8-9932-ac490679f902.png)

**Comment by vincentmorneau** [comment]
How does it become `cobalt.css`? I see in your src folder you have `/src/scss/app.scss`, so I am expecting your final files to be accessible with:
`https://localhost:4000/css/app.min.css`
or as a reference in APEX to:
`#APP_IMAGES#css/app#MIN#.css`

Does that make sense? How are you referencing the files yourself?

**Comment by Divyashree-Ramesh** [comment]
May be I was not clear. 

This is not my css file. I selected a theme 'Cobalt' for my script editor(for black background) in APEX builder. When I login to APEX builder through nitro, I get this error and my script editor is white. If I login without nitro, script editor is fine.

**Comment by vincentmorneau** [comment]
Ok got it. Makes sense now. I'll try later and will get back to you.

**Comment by vincentmorneau** [comment]
For some reason the following plugin from the APEX builder pulls the files from the wrong path:

![image](https://user-images.githubusercontent.com/5391291/38179314-c149694a-35ef-11e8-814b-d46c17f2693d.png)

And the regular code editor works fine:

![image](https://user-images.githubusercontent.com/5391291/38179316-d7141b76-35ef-11e8-865a-f4b25218cb34.png)

Since there are only 6 references across the APEX Builder, I'm going to flag this as `wontfix`. 

You can always open your regular APEX Builder URL to work on these parts of your development.

Thanks for reporting!
