### ISSUE TITLE
Could we edit HTML externally and sync it with apex-nitro then render it in APEX

### ISSUE THREAD

**Issue by mahmoudrabie** [OraOpenSource/apex-nitro#276]
Hi apex-nitro team

Could we edit HTML externally and sync it with apex-nitro then render it in APEX?
https://community.oracle.com/thread/4158780

I would appreciate your help and recommendations.

Regards
Mahmud

**Comment by rafael-trevisan** [comment]
That'd be a nice feature. 👍 

I have the same pain whenever I have to "design" any custom HTML inside a region or something like that. I always end up writing my HTML in an external editor and then CTRL+C/V it into APEX.

I remember Atom had an extension that whenever I was in any textarea element I could fire this Chrome Extension from Chrome and then edit in Atom. It's called "[Atomic Chrome](https://chrome.google.com/webstore/detail/atomic-chrome/lhaoghhllmiaaagaffababmkdllgfcmc)".

I'm using VS Code now and I haven't any similar extension for it.

Cheers

**Comment by vincentmorneau** [comment]
Mahmud,

I think I understand your requirement.

APEX renders HTML with templates, and templates are part of the meta data of the APEX tables (`wwv_flow_*`). APEX Nitro has no access to write to those tables, so that's off the chart.

I believe you want to import partial HTML from #APP_IMAGES# into your APEX page. Example: `#APP_IMAGES#/foo.html` should go into region `#nitro123` of page 1.

Step 1: Declare a JS variable to store `#APP_IMAGES#`.
![image](https://user-images.githubusercontent.com/5391291/42880332-e7551e4c-8a61-11e8-8a8c-3c7f502b8a8b.png)

Step 2: Identify the region container
![image](https://user-images.githubusercontent.com/5391291/42880358-031547d8-8a62-11e8-9b9d-9f9536eb2fcc.png)

Step 3: Have an html folder in your APEX Nitro file structure, and add a html file in there (`test.html`):
![image](https://user-images.githubusercontent.com/5391291/42880409-353d075a-8a62-11e8-8a8f-852c48f4e298.png)

Step 4:
In your JavaScript, define an IIFE (immediately invoked function) and load your html partial into your APEX page, under the region container defined in step 2:
![image](https://user-images.githubusercontent.com/5391291/42880507-9241cba2-8a62-11e8-9443-a33f4bafd7a2.png)

---

That's what makes the most sense to me. Does that work for you? Obviously that won't give you dynamic content like a PL/SQL region does, as the partial html file won't look for data in your database.

**Comment by mahmoudrabie** [comment]
PERFECT!

I think that will satisfy the requirement.

Is there any way other than using FavIcon HTML?

Regards
Mahmoud

**Comment by vincentmorneau** [comment]
You could have `var appImages = '#APP_IMAGES#';` on your page properties, but then you'd have to repeat that on every page.

I find that having it in Favicon HTML is the easiest approach.

**Comment by mahmoudrabie** [comment]
Thanks a lot.

**Comment by mahmoudrabie** [comment]
Yes, I understand you. 

**appImages** must be calculated in APEX then send to **apex-nitro**

**Comment by vincentmorneau** [comment]
That is correct, for resolving the path. Feel free to close the issue.

**Comment by mahmoudrabie** [comment]
Thanks again.
