### ISSUE TITLE
How do i setup the publishing config?

### ISSUE THREAD

**Issue by SugarfreeTX** [OraOpenSource/apex-nitro#288]
### Issue Description
I'm stuck on what to use for:
User:
Password:
host:
port:
connection type:

Everything is on my home computer. Node.js and SQLcl. I have Nitro and Apex communicating but i can't get it to publish the files. 
I tried the troubleshooting but I don't get far since I don't know how to find the information I need to complete the configuration. 

### APEX Nitro Version
Most recent

### Operating System
Windows10 home

### Node Version
8.12.0

### Browser
Chrome

### APEX Version
18.1

### Web Server
not sure

### Project configuration screenshot

![image](https://user-images.githubusercontent.com/41549429/46112932-065e8f80-c1b2-11e8-85a4-7a26c596032f.png)

**Comment by vincentmorneau** [comment]
Hi, that's a great question and I think it should be clearer in the doc. Your screenshot only shows the top part of the configuration, but I see you are trying to reach an application on apex.oracle.com, which will NOT work. In order to use APEX Nitro's publish feature, you need to have access to the database, which you do not on apex.oracle.com. Do you have any other environment you can use?

Are you familiar with a database connection string? Do you use SQL Developer?

The information you put in this "publish" section is required for connecting to the database using SQLcl. For instance, here's what I use to log in to my localhost environment:

User: dev
Password: devpassword
host: localhost
port: 32122
connection type: service name
service name: apex1810

**Comment by SugarfreeTX** [comment]
Okay now I see. I do not use an environment currently, but I do have SQL Plus that I use for learning. Could I use that? No, unfortunately I am not familiar with the SQL connection string. However, I really do appreciate you getting back to me and allowing the use of Nitro, it's allowed me to engage more with CSS and customizing my Apex applications. If I'll need a connection to a database, I'll see about setting up one to use with Apex. Thank you Vincent!

**Comment by vincentmorneau** [comment]
That makes sense.

APEX Nitro or not, having a personal development environment with SQL Development access is the best thing you can do for yourself (technologically speaking).

I personally set up a few APEX environments on my system with Docker; one for each APEX versions (5.0.4, 5.1.4, 18.1 and soon 18.2). You can follow this guide by @martindsouza https://github.com/martindsouza/docker-oracle-setup

Then you'll be able to use APEX Nitro publish feature.

Feel free to close this issue.

**Comment by SugarfreeTX** [comment]
Cool! Again, thanks for everything.
